gccxml_bin = r'D:\CppSource\Temp\CastXML\vcbuild\bin\RelWithDebInfo\castxml.exe'
gccxml_args = r'--castxml-gccxml -w -x c++ -std=c++14 -fms-compatibility-version=19 -D__GCCXML__'
premake_bin = r'premake5'
pyroot = r'C:\Python27'
make = r'mingw32-make'
